Repository zcash/librustzcash, pull requests merged in 2024-06, with the labels that each got.

#1405 Add and prune audits
  supply-chain/audits.toml
  supply-chain/imports.lock
Labels: dependencies

#1429 zcash_client_sqlite: Start documenting the table structures
  zcash_client_sqlite/src/wallet.rs
  zcash_client_sqlite/src/wallet/db.rs
  zcash_client_sqlite/src/wallet/init.rs
Labels: A-documentation, A-wallet

#1430 Improvements to the strategy implemented by `{fixed,standard,zip317}::SingleOutputChangeStrategy`
  zcash_client_backend/CHANGELOG.md
  zcash_client_backend/src/fees/common.rs
  zcash_client_backend/src/fees/zip317.rs
  zcash_client_sqlite/src/testing/pool.rs
Labels: A-wallet
